# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/garrett/Unreal/Unreal_Engine_5.7.1

TARGETS = \
	MechaMaker-Android-DebugGame  \
	MechaMaker-Android-Development  \
	MechaMaker-Android-Shipping  \
	MechaMaker-Linux-DebugGame  \
	MechaMaker-Linux-Development  \
	MechaMaker-Linux-Shipping  \
	MechaMaker-LinuxArm64-DebugGame  \
	MechaMaker-LinuxArm64-Development  \
	MechaMaker-LinuxArm64-Shipping  \
	MechaMaker \
	MechaMakerEditor-Linux-DebugGame  \
	MechaMakerEditor-Linux-Development  \
	MechaMakerEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MechaMakerEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MechaMakerEditor-Linux-Debug


MechaMaker-Android-DebugGame:
	 $(BUILD) MechaMaker Android DebugGame  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-Android-Development:
	 $(BUILD) MechaMaker Android Development  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-Android-Shipping:
	 $(BUILD) MechaMaker Android Shipping  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-Linux-DebugGame:
	 $(BUILD) MechaMaker Linux DebugGame  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-Linux-Development:
	 $(BUILD) MechaMaker Linux Development  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-Linux-Shipping:
	 $(BUILD) MechaMaker Linux Shipping  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-LinuxArm64-DebugGame:
	 $(BUILD) MechaMaker LinuxArm64 DebugGame  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-LinuxArm64-Development:
	 $(BUILD) MechaMaker LinuxArm64 Development  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker-LinuxArm64-Shipping:
	 $(BUILD) MechaMaker LinuxArm64 Shipping  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMaker: MechaMaker-Linux-Development

MechaMakerEditor-Linux-DebugGame:
	 $(BUILD) MechaMakerEditor Linux DebugGame  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMakerEditor-Linux-Development:
	 $(BUILD) MechaMakerEditor Linux Development  -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" $(ARGS)

MechaMakerEditor: MechaMakerEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/garrett/Desktop/Capstone/mecha-maker/MechaMaker.uproject" -Game 

.PHONY: $(TARGETS)
